VGA-Team2022/idol-road

Assets/Maeda.meta
Assets/Maeda/ScreenInput.cs
Assets/Maeda/ScreenInput.cs.meta
Assets/Maeda/Test.unity
Assets/Maeda/Test.unity.meta

#3 
フリックの上下左右が上手く取れないときがあるのできっちり取れるようにする

Editer上でマウス、ビルド時はスクリーンタッチで入力を受け取るようにした

---

Assets/Maeda/ScreenInput.cs

enumのFlickTypeをクラスの下に移動させた

---

Assets/Maeda/ScreenInput.cs
Assets/Maeda/Test.unity

おおむねフリックの判定を取れるようにした

---

Assets/Ohnari/GameManager.cs
Assets/Ohnari/GameTest.unity

押したらカウントが始まるボタンの作成

---

Assets/Editor/SEElementNameDrawer.cs
Assets/Editor/SEElementNameDrawer.cs.meta
Assets/shinohara/FlickSENames.cs
Assets/shinohara/FlickSENames.cs.meta
Assets/shinohara/SEPlay.cs

既にSEが再生されていれば再生中のSEを止めて新しくSEを鳴らすよう修正　SEの配列の要素名を変更する機能を作成

---

Assets/Animations/EnemyExplosionEffect/Explosion.anim
Assets/Prefabs/ExplosionEffect.prefab
Assets/shinohara/EnemyExplosionEffect.cs
Assets/shinohara/EnemyExplosionEffect.cs.meta
Assets/shinohara/TestScene.unity

Issue
#2
現在は単純に削除していますがのちのちは、オブジェクトプールなどに切り替えるかもしれません

敵の爆発エフェクトが終了したら自身を削除する機能を追加

---

Assets/shinohara/Enemy.cs
Assets/shinohara/TestScene.unity

倒した敵のカウントをする関数を受け取るActionを追加

---

Assets/Tsuguhiko/Prefabs.meta
Assets/Tsuguhiko/Prefabs/SettingObjects.prefab
Assets/Tsuguhiko/Prefabs/SettingObjects.prefab.meta
Assets/Tsuguhiko/Scenes/Proto_Bg.unity
Assets/Tsuguhiko/Scripts/Hit.cs
Assets/Tsuguhiko/Scripts/Hit.cs.meta
Assets/Tsuguhiko/Scripts/PlayerController.cs
Assets/Tsuguhiko/Scripts/PlayerMotion.cs
Assets/Tsuguhiko/Scripts/PlayerMotion.cs.meta
Assets/Tsuguhiko/Scripts/RoadGenerator.cs
Assets/Tsuguhiko/Scripts/RoadGenerator.cs.meta

背景スクロールの修正とボタン操作等の受付で動作する動きを止める関数と再開する関数を作成。

背景スクロールの修正＆動きを止める関数と再開する関数の実装。

---

Assets/Maeda/ScreenInput.cs

[update]タップでも敵が吹っ飛んでいたのでフリックでのみ飛んでいくようにした

---

Assets/Ohnari/GameManager.cs
Assets/Ohnari/GameTest.unity

スーパーアイドルタイムに映るための関数の作成。ゲームフラグのプロパティの作成

---

Assets/Ryu/Scripts/ResultManager.cs

リザルトマネージャークラスのシングルトン構造の訂正

---

Assets/Ryu/ryu.unity
Assets/Ryu/ryu.unity.meta
Assets/Scripts/ScreenInput.cs
Assets/Scripts/SuperIdolTime.cs

スーパーアイドルタイムのタップ数でゲージが増加するようにしました・自分で確認する用のシーンを作りました

---

Assets/Prefabs/Enemy.prefab
Assets/Scripts/Enemy.cs
Assets/Scripts/NormalEnemy.cs
Assets/Scripts/ScreenInput.cs

タスクに振り分けされていたものはできました、まだDebugでの表示になってしまうのと、通常ファン用のスクリプトしかできてないので、そこだけ把握お願いします。
#32

通常ファンのprefubの追加とコメントの追加、スクリプトの整理をおこないました。

---

Assets/Ryu/ryu.unity
Assets/Scripts/SuperIdolTime.cs

スーパーアイドルタイムの時間管理と終了処理の追加

---

Assets/Scripts/TapAct.cs
Assets/Tsuguhiko/Scenes/Title.unity
Assets/Tsuguhiko/Scripts/FadeManager2.cs
Assets/Tsuguhiko/Scripts/FadeManager2.cs.meta

#42 
フェードイン・アウトの処理追加（FadeManager2.csに書いてあります。)

FadeManagerにフェードイン・アウトの処理を追加

---

Assets/Scenes/αGameScene.unity

[update]αGameSceneコミットしなおし

---

Assets/Prefabs/Item/Item_Box.prefab
Assets/Scripts/Item/IdolPowerItem.cs
Assets/Scripts/Item/ItemGenerator.cs
Assets/Scripts/System/ScreenInput.cs
Assets/shinohara/Scripts.meta
Assets/shinohara/shinohara.unity
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/TagManager.asset

Issue
#83 
衝突した場合スタッシュ使ってください。

アイテム取得の機能を追加　アイテムが地面に到着したら消えるようにした

---

Assets/Prefabs/Enemy.meta
Assets/Prefabs/Enemy/RequestUI.prefab
Assets/Prefabs/Enemy/RequestUI.prefab.meta
Assets/Scripts/Enemy/RequestUIController.cs
Assets/Scripts/Enemy/RequestUIController.cs.meta

issue
#70
●残タスク
・ファンのプレハブに組み込む
・イラストを追加する

ファンサを表示するプレハブを作成　ファンサと吹き出しを変更するクラスを作成

---

Assets/Ryu/ryu.unity
Assets/Scripts/InGame/ResultManager.cs
Assets/Scripts/InGame/ResultSwitcher.cs
Assets/Scripts/InGame/ResultSwitcher.cs.meta
Assets/Scripts/System/ScreenInput.cs

#71
動画がうまく取れなかったので画像で失礼します
「Perfect 神」「Excellent 良」「Good 普通」が条件で分岐した結果で、
その一つ上のログがBad、Good、Perfect、(スーパーアイドルタイム中のPerfect)で内訳したログです。
結果の下のログに「昇格」がある場合はPerfectの数が一定数より多く、Good(普通)またはExcellent(良)からランクアップしています。
Inspectorの要素は上から、
・Excellent(良)以上なるためのBad判定の数の許容値。
・Perfect(神)に昇格するために必要なPerfectの数。
・Good(普通)からExcellent(良)に昇格するために必要なPerfectの数。
・デバッグする際の判定の数。
・デバッグする際のスーパーアイドルタイム中のPerfect数のランダム範囲。
になっています。
不明点あれば伝えてください！

リザルト条件のスクリプトを追加

---

Assets/Prefabs/Enemy/RequestWindow.prefab
Assets/Scripts/Enemy/RequestUIController.cs

Issue
#70
ファンは向かってくるのに要求は動かないという挙動を修正

UIとして表示していたファンサ要求をSpriteRendererを使用したものに変更

---

Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/System/ScreenInput.cs

[update]ScreenInputから呼ぶことで次のファンを出していたがファンが現在いるかどうかで次のファンを出すようにした

---

Assets/Prefabs/Enemy/Enemy.prefab
Assets/Prefabs/Enemy/EnemySpawner.prefab
Assets/Prefabs/Enemy/EnemySpawner.prefab.meta
Assets/Prefabs/Enemy/RequestWindow.prefab
Assets/Scripts/Enemy/Enemy.cs

ファンのプレハブに吹き出しを追加　ファンのスポナーをプレハブ化

---

Assets/Prefabs/Enemy/Enemy.prefab
Assets/Scripts/Enemy/Enemy.cs
Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/InGame/GameManager.cs

out判定になったらプレイヤーのHPを減らす処理を追加

---

Assets/Data.asset
Assets/Data.asset.meta
Assets/Scripts/InGame/ResultSwitcher.cs
Assets/Scripts/InGame/ResultSwitcherScriptableObject.cs
Assets/Scripts/InGame/ResultSwitcherScriptableObject.cs.meta

ResultSwitcherクラスの変数のScriptableObject化

---

Assets/Tsuguhiko/Scripts/BlidIn.cs
Assets/Tsuguhiko/Scripts/BlidIn.cs.meta

#82 フェードイン用のスクリプトを作成中 (一連の流れとプレハブは後ほど)

---

Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/InGame/GameManager.cs

[update]EnemySpawnが持っていたフラグなどをGameMangerが持つフラグと置き換えた

---

Assets/Prefabs/Combo.meta
Assets/Prefabs/Combo/BackGround.prefab
Assets/Prefabs/Combo/BackGround.prefab.meta
Assets/Prefabs/Combo/Chara.prefab
Assets/Prefabs/Combo/Chara.prefab.meta
Assets/Prefabs/Combo/CharaDownObj.prefab
Assets/Prefabs/Combo/CharaDownObj.prefab.meta
Assets/Prefabs/Combo/FadeObj.prefab
Assets/Prefabs/Combo/FadeObj.prefab.meta

Asset直下にComboフォルダを作成してそこにスプライトを移動させた

---

Assets/Prefabs/UI/WarningTimeLine.prefab
Assets/Prefabs/UI/WarningTimeLine.prefab.meta
Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/InGame/GameManager.cs

[add]ボス戦時のタイムラインを作成(タイムライン中の画像は上げていない)

---

Assets/Prefabs/UI/InGameCanvas.prefab
Assets/Scripts/InGame/InGameUIController.cs

UIにコンボを表示するテキストを追加　コンボ数テキストを更新する機能を追加

---

Assets/Animations/ComboAnimation/UI.meta
Assets/Animations/ComboAnimation/UI/UIBackGround.controller
Assets/Animations/ComboAnimation/UI/UIBackGround.controller.meta
Assets/Animations/ComboAnimation/UI/UIBackGroundAnim.anim
Assets/Animations/ComboAnimation/UI/UIBackGroundAnim.anim.meta
Assets/Animations/ComboAnimation/UI/UICharacter.controller
Assets/Animations/ComboAnimation/UI/UICharacter.controller.meta
Assets/Animations/ComboAnimation/UI/UICharacterAnim.anim
Assets/Animations/ComboAnimation/UI/UICharacterAnim.anim.meta
Assets/Prefabs/UI/InGameCanvas.prefab
Assets/Scripts/InGame/InGameUIController.cs

Issue
#56
コンボを表示するプレハブをUIに対応出来るようにしました。

一定数コンボが続いた時のイラストを表示する機能を修正　コンボイラストを表示するプレハブ（UI）を作成

---

Assets/Scripts/GameState.meta
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/GameState/BossTime.cs.meta
Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/GameState/GameEnd.cs.meta
Assets/Scripts/GameState/GameStart.cs
Assets/Scripts/GameState/GameStart.cs.meta
Assets/Scripts/GameState/IdleTime.cs
Assets/Scripts/GameState/IdleTime.cs.meta
Assets/Scripts/GameState/Playing.cs
Assets/Scripts/GameState/Playing.cs.meta
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/Interface.meta
Assets/Scripts/Interface/IState.cs
Assets/Scripts/Interface/IState.cs.meta
Assets/Scripts/System/ScreenInput.cs

Issue
#33 
それに伴う各状態を管理するクラスを作成

インゲームの進行をstateパターンで管理するようにした

---

Assets/Prefabs/UI/FadeCanvas.prefab
Assets/Scripts/Enemy/Enemy.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/GameState/GameStart.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/System/FadeController.cs

Issue
#33 
リストに追加、リストから削除を行う機能を追加

画面に表示されているファンのリストを作成

---

Assets/Animations/TimeLine.meta
Assets/Animations/TimeLine/WarningTimeline.playable
Assets/Animations/TimeLine/WarningTimeline.playable.meta
Assets/Sprites/Boss/WARNING!テープ.png
Assets/Sprites/Boss/WARNING!テープ.png.meta

[add]ボス戦開始時のタイムラインを作成

---

Assets/Scenes/StageSelectScene.unity
Assets/Scenes/StageSelectScene.unity.meta
Assets/Scripts/StageSelect.meta
Assets/Scripts/StageSelect/StageSelectController.cs
Assets/Scripts/StageSelect/StageSelectController.cs.meta

ステージセレクトの難易度によってImageの色が変わるようにした。

---

Assets/Scenes/MainScene/ResultScene.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scenes/Scripts/StageSelect/StageSelectController.cs
Assets/Scenes/Scripts/StageSelect/StageSelectController.cs.meta
Assets/Scenes/Scripts/Title/TitleManager.cs
Assets/Scenes/Scripts/Title/TitleManager.cs.meta
Assets/Scenes/StageSelectScene.unity

タイトル遷移の際のPanelのフェードインフェードアウトの作成。TitleManagerでシーンの名前の変更が可能

---

Assets/Scenes/αGameScene.unity
Assets/Scripts/Enemy/EnemySpawner.cs

Enemyが生成する場所を変えるようにEnemySpawnerを修正した。

生成する場所を変えられるようにEnemySpawnerスクリプトを修正

---

Assets/Animations/CommentAnimations.meta
Assets/Animations/CommentAnimations/fan1.controller
Assets/Animations/CommentAnimations/fan1.controller.meta
Assets/Animations/CommentAnimations/fan1Animation.anim
Assets/Animations/CommentAnimations/fan1Animation.anim.meta
Assets/Animations/CommentAnimations/fan2.controller
Assets/Animations/CommentAnimations/fan2.controller.meta
Assets/Animations/CommentAnimations/fan2Animation.anim
Assets/Animations/CommentAnimations/fan2Animation.anim.meta
Assets/Animations/CommentAnimations/fan3.controller
Assets/Animations/CommentAnimations/fan3.controller.meta
Assets/Animations/CommentAnimations/fan3Animation.anim
Assets/Animations/CommentAnimations/fan3Animation.anim.meta
Assets/Animations/CommentAnimations/fan4.controller
Assets/Animations/CommentAnimations/fan4.controller.meta
Assets/Animations/CommentAnimations/fan4Animation.anim
Assets/Animations/CommentAnimations/fan4Animation.anim.meta
Assets/Animations/CommentAnimations/fan5.controller
Assets/Animations/CommentAnimations/fan5.controller.meta
Assets/Animations/CommentAnimations/fan5Animation.anim
Assets/Animations/CommentAnimations/fan5Animation.anim.meta
Assets/Prefabs/UI/ResultUI.prefab
Assets/Prefabs/UI/Text.prefab
Assets/Prefabs/UI/Text.prefab.meta
Assets/Sprites/Result/マット_コメント吹き出し.png.meta

リザルト画面のコメントのプレファブの作成とアニメーションでうごくように設定しました。
プランナーの方でもアニメーションの変更とコメントを変えるようにしました。
#129

リザルト画面時にコメントの配置とコメントがアニメーションででてくるようにした。プランナーさんでも設定可能。

---

Assets/Prefabs/Enemy/Enemy.prefab
Assets/Prefabs/UI/WarningTimeLine.prefab
Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Enemy/Enemy.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/System/ScreenInput.cs
Assets/Sprites/Enemy/強欲BBA.png.meta

Issue
#151 
#150 
ボスステージを開始に演出が再生されるようにした。
ボスステージ中は敵のイラストが変更されるようにした。

ファンが生成される度にステージスクロールが開始する問題を解決

---

Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Title/TitleManager.cs

ストーリーボタンとクレジットボタンの設置。ストーリーのボタンが押されるとポップアップがでるのと、ポップアップがでたあとにタップすると閉じるようになっている
#147

ストーリーボタンとクレジットボタンの設置。ポップアップあたりの設定

---

Assets/Ohnari/GameTest.unity
Assets/Prefabs/UI/ResultUI.prefab
Assets/Scripts/Result/ResultSwitcher.cs
Assets/Scripts/Result/ResultUIController.cs

スコアがリザルトにアニメーション付きで表示されるようにした。$"{}"の中身、第三引数の変数、値を削除してコメントされてる変数のコメントを削除するとゲーム終了後の動作確認が取れる

---

Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Title/TitleManager.cs

タイトルシーンを修正

---

Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Scripts/Enemy/BossEnemy.cs
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/InGame/GameManager.cs

ボスステージ開始から一定の時間経過するとボスが近づいてくる機能を追加　ファンの生成を一時停止する機能を追加

---

Assets/Animations/BossEnemy.meta
Assets/Animations/BossEnemy/BossEnemyController.controller
Assets/Animations/BossEnemy/BossEnemyController.controller.meta
Assets/Animations/BossEnemy/Left.anim
Assets/Animations/BossEnemy/Left.anim.meta
Assets/Animations/BossEnemy/Right.anim
Assets/Animations/BossEnemy/Right.anim.meta
Assets/Animations/BossEnemy/Up.anim
Assets/Animations/BossEnemy/Up.anim.meta
Assets/Animations/NomalEnemy.meta
Assets/Animations/NomalEnemy/Left.anim
Assets/Animations/NomalEnemy/Left.anim.meta
Assets/Animations/NomalEnemy/NomalEnemyController.controller
Assets/Animations/NomalEnemy/NomalEnemyController.controller.meta
Assets/Animations/NomalEnemy/Right.anim
Assets/Animations/NomalEnemy/Right.anim.meta
Assets/Animations/NomalEnemy/Up.anim
Assets/Animations/NomalEnemy/Up.anim.meta
Assets/Animations/WallEnemy/WallEnemy.controller
Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Prefabs/Enemy/WallEnemy.prefab
Assets/Scripts/Enemy/BossEnemy.cs
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/Enemy/NormalEnemy.cs
Assets/Scripts/Enemy/WallEnemy.cs
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/InGame/GameManager.cs

吹き飛ぶ演出をDoTweenからUnityのアニメーションに切り替えた

---

Assets/Prefabs/Audio/AudioManager.prefab
Assets/Prefabs/Audio/CRIWARE.prefab
Assets/Prefabs/UI/InGameCanvas.prefab
Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/System/ScreenInput.cs

入力判定バグを解決　壁ファンのダメージを1に調整

---

Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Title/TitleManager.cs

Issue
#175
フェードにかかる時間はプランナーさんに設定してもらう

フェード中でもシーン遷移を可能にした　フェード中はボイスを流さないようにした　ポップアップ表示中はシーン遷移させない機能を追加

---

Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/StageSelect/PlayUiCanvas.cs
Assets/Scripts/StageSelect/PlayUiCanvas.cs.meta
Assets/Scripts/StageSelect/StageSelectController.cs

ステージセレクトシーンを編集

---

Assets/GameParameter/Nomal/Parameter/InGame.asset
Assets/Scenes/MainScene/InGame.unity
Assets/Scripts/GameParameter/LevelManager.cs
Assets/Scripts/GameState/GameStart.cs
Assets/Scripts/InGame/GameManager.cs

Issue
#179
#174
HPの位置・大きさはもう一度チームメンバーで確認を行う。

ファン対応中でもゲームが進行するようにした　HPUIの位置・大きさを調整した

---

Assets/GameParameter/Nomal/Enemy/Boss.asset
Assets/GameParameter/Nomal/Enemy/Nomal.asset
Assets/GameParameter/Nomal/Enemy/Wall2.asset
Assets/GameParameter/Nomal/Enemy/Wall3.asset
Assets/GameParameter/Nomal/Parameter/InGame.asset
Assets/GameParameter/Nomal/Parameter/Order.asset
Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Prefabs/Enemy/EnemySpawner.prefab
Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Prefabs/Enemy/WallEnemy2.prefab
Assets/Prefabs/Enemy/WallEnemy3.prefab
Assets/Scripts/Enemy/BossEnemy.cs
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/Enemy/NormalEnemy.cs
Assets/Scripts/GameParameter/EnemyOrderParameter.cs

Issue
#183 
・仮で難易度Nomalの生成順番を設定しました。
・待機時間（敵がいない）を設定出来るようにしました。

生成順番のパラメーターをスポナークラスに適用

---

Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Prefabs/Enemy/WallEnemy2.prefab
Assets/Prefabs/Enemy/WallEnemy3.prefab
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpriteChange.cs
Assets/Scripts/Enemy/NormalEnemy.cs

通常ファン生成時どのファンを生成したか分かるようにした

---

Assets/GameParameter/Nomal/Parameter/Order.asset
Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/Audio/NomalEnemyVoice.cs
Assets/Scripts/Audio/NomalEnemyVoice.cs.meta
Assets/Scripts/Enemy/NormalEnemy.cs
Assets/Scripts/Enemy/WallEnemy.cs

通常ファンの種類に合わせたボイスを再生出来るようにした

---

Assets/Animations/BossEnemy/BossEnemyController.controller
Assets/Animations/BossEnemy/Walk.anim
Assets/Animations/BossEnemy/Walk.anim.meta

強欲ボスの歩きアニメーションを作成

---

Assets/GameParameter/Nomal/Parameter/Result.asset
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/GameParameter/EnemyParameter.cs
Assets/Scripts/GameParameter/ResultParameter.cs

Issue
#196
#197
EnemyBaseに倒された時アイドルパワー増加させる処理を追加

敵を倒した時に獲得出来るアイドルパワー量を変更できるようにした　リザルト画面で表示するファンセリフを設定できるようにした

---

Assets/GameParameter/Nomal/Parameter/Result.asset
Assets/Prefabs/UI/FanCommentObjects.prefab
Assets/Prefabs/UI/FanCommentObjects.prefab.meta
Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/Result/ResultUIController.cs

リザルトのファンコメントUIの画面調整

---

Assets/GameParameter/Nomal/Enemy/Boss.asset
Assets/GameParameter/Nomal/Parameter/InGame.asset
Assets/GameParameter/Nomal/Parameter/Order.asset
Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Prefabs/Enemy/WallEnemy2.prefab
Assets/Prefabs/Enemy/WallEnemy3.prefab
Assets/Scripts/Enemy/BossEnemy.cs
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/GameState/GameStart.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/System/StageScroller.cs

ボスを倒せるようにした

---

Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/Result/ResultUIController.cs
Assets/Scripts/StageSelect/StageSelectController.cs
Assets/Scripts/Title/TitleManager.cs

遷移中に他の遷移ボタンを押したらその遷移が開始される問題を解決

---

Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/Audio/AudioManager.cs

どのシーンからでも音を出せるようにした

---

Assets/Graphics/Sprites/Player/吹き出しラフ_GOOD_ウインク.png.meta
Assets/Graphics/Sprites/Player/吹き出しラフ_GOOD_投げキス.png.meta
Assets/Prefabs/Player.meta
Assets/Prefabs/Player/吹き出しラフ_GOOD_ウインク.prefab
Assets/Prefabs/Player/吹き出しラフ_GOOD_ウインク.prefab.meta
Assets/Prefabs/Player/吹き出しラフ_GOOD_投げキス.prefab
Assets/Prefabs/Player/吹き出しラフ_GOOD_投げキス.prefab.meta
Assets/Scenes/MainScene/InGame.unity
Assets/Scripts/InGame/PlayerMotion.cs

フリック後の吹き出し表示時間は、playerMotionクラスのfansaShowTime変数で変更可能。
#223

スプライトのpixcelUnit変更。PrefabにPlayerフォルダ追加。投げキスとウィンクの吹き出しを表示させるようにした。

---

Assets/GameParameter/Nomal/Parameter/Order.asset
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/GameParameter/EnemyOrderParameter.cs

ファン(エネミー)の要求ファンサービスをランダムにできるようにした

---

Assets/GameParameter/Nomal/Parameter/Result.asset
Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/Result/ResultManager.cs
Assets/Scripts/Result/ResultUIController.cs

インゲーム終了時にBGMを止めるようにした

---

Assets/Prefabs/UI/InGameCanvas.prefab
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scenes/MainScene/StageSelectScene.unity

Issue
#228
スマホのサイズに合わるようにして解決したので、後々どのスマホに対応できるようにする

スマホで実行した際にUI配置が崩れる問題を解決

---

Assets/Scripts/GameParameter/ResultParameter.cs
Assets/Scripts/Result/ResultManager.cs
Assets/Scripts/Result/ResultUIController.cs

リザルト時評価毎にコメントが変わるようにした

---

Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/Result/PlayResult.cs

前回のプレイ結果をリセット出来るようにした

---

Assets/Animations/TimeLine/WarningTimeline.playable
Assets/Prefabs/UI/WarningTimeLine.prefab

フェイドの追加とアラームにあわせて修正しました
#214 
#219

timelineの修正とフェイドの追加

---

Assets/Scenes/MainScene/ResultScene.unity
Assets/Scripts/Result/ResultUIController.cs

テキストの後ろの枠をなくしてoutLineで文字の強調をした。

---

Assets/Scenes/MainScene/InGame.unity
Assets/Scripts/Audio/AudioManager.cs
Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/Result/ResultManager.cs
Assets/Scripts/Result/ResultUIController.cs

ゲームクリア時にタクシー音が再生されたままシーン遷移する問題を解決

---

Assets/Scenes/MainScene/InGame.unity
Assets/Scripts/GameParameter/LevelManager.cs
Assets/Scripts/InGame/GameManager.cs

難易度をインスペクターで設定出来るようにした

---

Assets/Animations/TimeLine/WarningTimeline.playable

TimeLineの修正

---

Assets/Prefabs/SuperIdolTime/SuperIdolTImeFrontCanvas.prefab
Assets/Scenes/MainScene/InGame.unity

スーパーアイドルタイムのUI調整

---

Assets/Scripts/Item/ItemGenerator.cs

#278
リストを使用しない場合はbool型の「Random Generator」にチェックを入れれば解決します。

[bug]設定したアイテムを全て生成し終えた時にIndexOutが出るエラーを修正

---

Assets/GameParameter/Normal/IdolTime.asset
Assets/GameParameter/Normal/InGame.asset
Assets/GameParameter/Normal/Result.asset

ゲームパラメーターを調整

---

Assets/GameParameter/Normal/Result.asset

行った作業内容をここに記載する

---

Assets/Prefabs/UI/TutorialCanvas.prefab
Assets/Prefabs/UI/TutorialCanvas.prefab.meta
Assets/Scenes/MainScene/StageSelectScene.unity

チュートリアルの中身の作成

---

Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/Result/ResultManager.cs
Assets/Scripts/Result/ResultUIController.cs
Assets/Scripts/StageSelect/PlayUiCanvas.cs
Assets/Scripts/StageSelect/StageSelectManager.cs
Assets/Scripts/Title/TitleManager.cs

タイトルBGMを追加、　リザルトのドラムロールを追加

---

Assets/Prefabs/UI/CreditCanvas.prefab
Assets/Prefabs/UI/StoryCanvas.prefab
Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/StageSelect/MenuController.cs
Assets/Scripts/Story/StoryPrinter.cs

Issue
#306 
タイトル表示時と強制表示時の処理を修正しました。

ストーリー表示機能を修正

---

Assets/GameParameter/Easy/Combo.asset
Assets/GameParameter/Easy/Combo.asset.meta
Assets/GameParameter/Hard/Combo.asset
Assets/GameParameter/Hard/Combo.asset.meta
Assets/GameParameter/Normal/Combo.asset
Assets/GameParameter/Normal/Combo.asset.meta
Assets/Resources/EasyLevel.asset
Assets/Resources/HardLevel.asset
Assets/Resources/NomalLevel.asset
Assets/Scripts/GameParameter/ComboParameter.cs
Assets/Scripts/GameParameter/ComboParameter.cs.meta
Assets/Scripts/GameParameter/GameParameter.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/InGame/InGameUIController.cs

[add]コンボ数で表示するイラストを設定するComboParameterを作成

---

Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/Result/ResultManager.cs

失敗時にタクシー音が何度も再生する問題を解決する

---

Assets/Scripts/Enemy/BossEnemy.cs
Assets/Scripts/Enemy/NormalEnemy.cs
Assets/Scripts/Enemy/WallEnemy.cs
Assets/Scripts/GameState/BossTime.cs
Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/System/ScreenInput.cs
Assets/Scripts/Title/TitleManager.cs

サウンドの追加と音量調整を行った

---

Assets/Scripts/InGame/GameManager.cs

コンボ時に出ていたエラーを解決

---

Assets/Scripts/Enemy/EnemySpawner.cs

ボス直前に壁ファンを配置するとエラーが出る問題を解決

---

Assets/Scenes/MainScene/StageSelectScene.unity
Assets/Scripts/StageSelect/MenuController.cs
Assets/Scripts/Story/StoryPrinter.cs

Issue
#325
BGMが再度最初から再生される問題がある。

二回目以降はストーリーと遊び方UIの強制表示をしないようにした

---

Assets/Prefabs/Enemy/BossEnemy.prefab
Assets/Prefabs/Enemy/ExplosionEffect.prefab
Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Prefabs/Enemy/RequestWindow.prefab
Assets/Prefabs/Item/Bouquet.prefab
Assets/Prefabs/Item/Money.prefab
Assets/Prefabs/Item/Present.prefab
Assets/Prefabs/Item/StuffedBear.prefab
Assets/Scenes/MainScene/InGame.unity

アイテムが必ず敵の前を通過するようにレイヤー順番を調整

---

Assets/GameParameter/Normal/Result.asset
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scripts/GameParameter/LevelManager.cs
Assets/Scripts/Result/ResultManager.cs
Assets/Scripts/Result/ResultUIController.cs
ProjectSettings/EditorBuildSettings.asset
UserSettings/Layouts/default-2021.dwlt

リザルトにコンボとスーパーアイドルタイムをあわせたボーナススコアの追加。それに伴うコメントの訂正や定数の書き換えを行った。

---

Assets/Graphics/Sprites/BackGround/ver2/街頭修正1.png
Assets/Graphics/Sprites/BackGround/ver2/街頭修正1.png.meta
Assets/Graphics/Sprites/BackGround/ver2/街頭修正2.png
Assets/Graphics/Sprites/BackGround/ver2/街頭修正2.png.meta
Assets/Graphics/Sprites/PlayingUI/画像_2023-01-07_145911986.png
Assets/Graphics/Sprites/PlayingUI/画像_2023-01-07_150005172.png
Assets/Graphics/Sprites/PlayingUI/画像_2023-01-07_150150232.png
Assets/Graphics/Sprites/PlayingUI/画像_2023-01-07_150328203.png
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明1ページ目.png
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明1ページ目.png.meta
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明2ページ目.png
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明2ページ目.png.meta
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明3ページ目.png
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明3ページ目.png.meta
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明4ページ目.png
Assets/Graphics/Sprites/PlayingUI/遊び方画面説明4ページ目.png.meta
Assets/Scenes/MainScene/StageSelectScene.unity

街灯イラストと遊び方UIのイラストを差し替えた　不要なイラストを削除

---

Assets/Animations/Title.meta
Assets/Animations/Title/TapToStart.anim
Assets/Animations/Title/TapToStart.anim.meta
Assets/Animations/Title/TapToStart.controller
Assets/Animations/Title/TapToStart.controller.meta
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/System/OutLineController.cs
Assets/Scripts/System/OutLineController.cs.meta

[add]Titleのスタートボタンを点滅させるアニメーションとアウトラインを点滅させるスクリプトを作成した

---

Assets/Scenes/MainScene/InGame.unity

コンボ数UIのフォント変更・調整

---

Assets/Scripts/Enemy/EnemySpawner.cs
Assets/Scripts/GameParameter/EnemyOrderParameter.cs

Issue
#332
1=6.72秒 2=4.8f 3=2.88f 4=0.96で作成しました。

ボス戦での敵の生成間隔を作成

---

Assets/Materials/LiberationSans SDF - TapToStart.mat
Assets/Materials/LiberationSans SDF - TapToStart.mat.meta

[add]タイトルのスタートボタンのアウトラインマテリアルを作成

---

Assets/Prefabs/SuperIdolTime/SuperIdolTimeBackCanvas.prefab
Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/ResultScene.unity
Assets/Scripts/Enemy/EnemyBase.cs
Assets/Scripts/GameState/IdolTime.cs
Assets/Scripts/InGame/GameManager.cs
Assets/Scripts/InGame/InGameUIController.cs
Assets/Scripts/InGame/SuperIdolTime.cs
Assets/Scripts/Item/ItemGenerator.cs

スーパーアイドルタイム移行時に発生していたバグの修正、スーパーアイドルタイムの発動回数が一回だけにする調整、リザルトシーンの表示調整

---

Assets/Prefabs/SuperIdolTime/SuperIdolTimeBackCanvas.prefab
Assets/Scenes/MainScene/InGame.unity

スーパーアイドルタイムのパーティクルの位置調整

---

Assets/Animations/EnemyExplosionEffect/ExpAnimator.controller
Assets/Animations/EnemyExplosionEffect/Explosion.anim
Assets/Prefabs/Enemy/ExplosionEffect.prefab

爆発エフェクトのSprite差し替えとアニメーション編集完了

#302 爆発エフェクトのSprite差し替えとアニメーション編集が終わりました

---

Assets/Scenes/MainScene/StageSelectScene.unity

メニュー画面と強制表示時で遊び方UIのボタンを変える

---

Assets/Scripts/Audio/AudioManager.cs
Assets/Scripts/GameState/IdolTime.cs
Assets/Scripts/InGame/SuperIdolTime.cs

アイドルタイムのBGMを追加

---

Assets/Prefabs/UI/CreditCanvas.prefab
Assets/Scenes/MainScene/InGame.unity

クレジットUIの中身を作成

---

Assets/Animations/SuperIdolTimeFans/SlideMiddleFan.anim
Assets/Animations/SuperIdolTimeFans/SlideUpFan.anim
Assets/Animations/SuperIdolTimeFans/SliedeDownFan.anim
Assets/Scenes/MainScene/InGame.unity
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/InGame/PlayerMotion.cs

タイトルのクレジットの「戻るボタン」が反応しないことの修正、
スーパーアイドルタイム時のスライドしてくる前のファンの位置調整

SDキャラのアクションに応じたスプライトの調整

---

Assets/GameParameter/Easy/Combo.asset
Assets/GameParameter/Hard/Combo.asset
Assets/GameParameter/Normal/2.asset
Assets/GameParameter/Normal/IdolTime.asset
Assets/Graphics/Sprites/Combo/10コンボ.png
Assets/Graphics/Sprites/Combo/10コンボ.png.meta
Assets/Graphics/Sprites/Combo/15コンボ.png
Assets/Graphics/Sprites/Combo/15コンボ.png.meta
Assets/Graphics/Sprites/Combo/20コンボ.png
Assets/Graphics/Sprites/Combo/20コンボ.png.meta
Assets/Graphics/Sprites/Combo/25コンボ.png
Assets/Graphics/Sprites/Combo/25コンボ.png.meta
Assets/Graphics/Sprites/Combo/30コンボ.png
Assets/Graphics/Sprites/Combo/30コンボ.png.meta
Assets/Graphics/Sprites/Combo/35コンボ.png
Assets/Graphics/Sprites/Combo/35コンボ.png.meta
Assets/Graphics/Sprites/Combo/40コンボ.png
Assets/Graphics/Sprites/Combo/40コンボ.png.meta
Assets/Graphics/Sprites/Combo/5コンボ.png
Assets/Graphics/Sprites/Combo/5コンボ.png.meta
Assets/Graphics/Sprites/Combo/ウインク_再修正.png
Assets/Graphics/Sprites/Combo/サイン_再修正.png
Assets/Graphics/Sprites/Combo/ポーズ_再修正.png
Assets/Graphics/Sprites/Combo/投げキッス_再修正.png
Assets/Scenes/MainScene/Title.unity
Assets/Scripts/GameParameter/LevelManager.cs

コンボイラストの差し替え　コンボパラメーターを調整

---

Assets/Prefabs/Enemy/NomalEnemy.prefab
Assets/Prefabs/Enemy/WallEnemy2.prefab
Assets/Prefabs/Enemy/WallEnemy3.prefab

インゲームのレイヤー問題の解決

---

Assets/GameParameter/Easy/Enemy/Boss.asset
Assets/GameParameter/Easy/Enemy/Nomal.asset
Assets/GameParameter/Easy/Enemy/Wall2.asset
Assets/GameParameter/Easy/Item.asset
Assets/GameParameter/Easy/Order.asset
Assets/GameParameter/Easy/Result.asset

イージーのパラメーターを調整　ボスが倒せない問題解決

---

Assets/Scripts/Audio/AudioManager.cs
Assets/Scripts/StageSelect/StageSelectManager.cs

Issue
#368
BGMが再生されているか調べる関数を作成しました。

タイトルBGMが最初から再生される問題を解決

---

Assets/Scripts/GameState/GameEnd.cs
Assets/Scripts/GameState/GameStart.cs
Assets/Scripts/GameState/IdolTime.cs
Assets/Scripts/InGame/PlayerMotion.cs
Assets/Scripts/System/ScreenInput.cs

フェード中に入力が取れる問題を解決

---

Assets/Animations/Menu/Tutorial/LeftButton .controller
Assets/Animations/Menu/Tutorial/LeftButton .controller.meta
Assets/Animations/Menu/Tutorial/LeftButton.anim
Assets/Animations/Menu/Tutorial/LeftButton.anim.meta
Assets/Animations/Menu/Tutorial/RightButton.anim
Assets/Animations/Menu/Tutorial/RightButton.anim.meta
Assets/Animations/Menu/Tutorial/RightButton.controller
Assets/Animations/Menu/Tutorial/RightButton.controller.meta
Assets/Prefabs/UI/TutorialCanvas.prefab

#386　両矢印のアニメーションを加えました
